---
abstract: 'Swat command'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Command-swat
no_index:
  directory:
    - inc
    - t
requires:
  Mojolicious: 0
  swat: '>= 0.1.67'
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.5
